# Generated by Django 6.0.2 on 2026-02-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Full product name. Example: 'UltraTech OPC 53 Grade Cement'", max_length=200)),
                ('brand', models.CharField(help_text="Brand name. Example: 'UltraTech', 'JSW Steel', 'Asian Paints'", max_length=100)),
                ('manufacturer', models.CharField(blank=True, help_text='Company that manufactures the product. Often same as brand.', max_length=200)),
                ('category', models.CharField(choices=[('cement', 'Cement'), ('steel', 'Steel & TMT Bars'), ('blocks', 'Blocks & Bricks'), ('paint', 'Paint & Coatings'), ('plumbing', 'Plumbing & Sanitary'), ('electrical', 'Electrical'), ('hardware', 'Hardware & Fasteners'), ('roofing', 'Roofing'), ('flooring', 'Flooring & Tiles'), ('other', 'Other')], db_index=True, max_length=20)),
                ('subcategory', models.CharField(blank=True, help_text="Optional. Example: 'OPC 53 Grade', 'TMT Fe500D', 'Premium Emulsion'", max_length=100)),
                ('description', models.TextField(help_text='Detailed product description. What it is, what it does, key benefits.')),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Technical specs as key-value pairs. Example: {"strength": "53 MPa"}')),
                ('price', models.DecimalField(decimal_places=2, help_text='Typical market price. Example: 385.00 (₹385 per bag)', max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, help_text='Maximum Retail Price (printed on packaging). No shop can charge above this.', max_digits=10)),
                ('unit', models.CharField(help_text="Unit of measurement. Examples: 'bag', 'kg', 'piece', 'litre', 'sqft', 'meter'", max_length=50)),
                ('is_code', models.CharField(blank=True, help_text="Indian Standard code. Example: 'IS 269:2015' for OPC cement.", max_length=100)),
                ('hot_dry', models.BooleanField(db_index=True, default=False, help_text='Rajasthan, Gujarat interior, Telangana plateau, interior Karnataka', verbose_name='Suitable for Hot & Dry Climates')),
                ('coastal_humid', models.BooleanField(db_index=True, default=False, help_text='Kerala coast, Mumbai, Chennai, Goa, Konkan, coastal Andhra/Odisha', verbose_name='Suitable for Coastal & Humid Climates')),
                ('heavy_rainfall', models.BooleanField(db_index=True, default=False, help_text='Kerala (2500mm+ annual rainfall), Northeast India, Western Ghats, Konkan', verbose_name='Suitable for Heavy Rainfall Regions')),
                ('cold_hilly', models.BooleanField(db_index=True, default=False, help_text='Himachal Pradesh, Uttarakhand, J&K, Sikkim, hill stations', verbose_name='Suitable for Cold & Hilly Regions')),
                ('cyclone_prone', models.BooleanField(db_index=True, default=False, help_text='Odisha coast, Tamil Nadu coast, Andhra coast (cyclone belt)', verbose_name='Suitable for Cyclone-Prone Coastal Areas')),
                ('seismic_zone', models.CharField(blank=True, choices=[('Zone II', 'Zone II (Low Damage Risk)'), ('Zone III', 'Zone III (Moderate Damage Risk)'), ('Zone IV', 'Zone IV (High Damage Risk)'), ('Zone V', 'Zone V (Very High Damage Risk)')], help_text='Minimum seismic zone this product is certified for. Leave blank if not relevant.', max_length=20)),
                ('states_available', models.JSONField(blank=True, default=list, help_text='List of states where product is available. Example: ["Kerala", "Tamil Nadu"]')),
                ('regional_notes', models.TextField(blank=True, help_text="Special notes for specific regions. Example: 'Not recommended for high-altitude (>2000m) construction due to freeze-thaw cycles.'")),
                ('primary_image', models.ImageField(blank=True, help_text='Main product image. Recommended: 800×800px square, max 2MB.', null=True, upload_to='products/')),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated URL identifier. Leave blank — generated from product name.', max_length=250, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Uncheck to hide product from the catalog without deleting it.')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('rating_breakdown', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='product_category_active_idx')],
            },
        ),
    ]
