# Generated by Django 6.0.2 on 2026-02-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seismic_zone',
            field=models.CharField(blank=True, choices=[('Zone II', 'Zone II (Low Damage Risk)'), ('Zone III', 'Zone III (Moderate Damage Risk)'), ('Zone IV', 'Zone IV (High Damage Risk)'), ('Zone V', 'Zone V (Very High Damage Risk)')], help_text='Minimum seismic zone this product is certified for. Leave blank if not relevant.', max_length=20, null=True),
        ),
    ]
