# Generated by Django 6.0.2 on 2026-02-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_seismic_zone_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cement', 'Cement'), ('steel', 'Steel & TMT Bars'), ('brick', 'Bricks & Blocks'), ('sand', 'Sand'), ('aggregate', 'Aggregate'), ('tile', 'Tiles & Flooring'), ('paint', 'Paint & Coatings'), ('waterproofing', 'Waterproofing')], db_index=True, max_length=20),
        ),
    ]
