# Generated by Django 6.0.2 on 2026-02-24 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_fix_category_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='Direct URL to the image. Must be publicly accessible.', max_length=1000)),
                ('caption', models.CharField(blank=True, help_text="Optional caption. Example: 'Front view', 'Application on wall'", max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Shown on product list cards. Only one image per product should be primary.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Lower number = shown first in gallery.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'db_table': 'product_images',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
