# Generated by Django 6.0.2 on 2026-03-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_confidence',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', help_text='Confidence in the price accuracy.', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price_source',
            field=models.CharField(choices=[('pwd_sor', 'Kerala PWD Schedule of Rates'), ('data_gov', 'data.gov.in API'), ('admin', 'Admin Entered'), ('ai_estimate', 'AI Estimate'), ('seed_baseline', 'Seed Baseline')], default='seed_baseline', help_text='Where this price was sourced from.', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='price_source_reference',
            field=models.CharField(blank=True, default='', help_text='Reference citation for this price (e.g., document name, URL).', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='price_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the price was last verified/updated.', null=True),
        ),
    ]
