# Generated by Django 6.0.2 on 2026-03-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_view_history_saved_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phase',
            field=models.CharField(blank=True, choices=[('foundation', 'Foundation & Substructure'), ('framing', 'Framing & Structure'), ('exterior', 'Exterior & Roofing'), ('roughin', 'Rough-In (Plumbing & Electrical)'), ('finishing', 'Interior Finishing')], db_index=True, help_text='Construction phase this material is primarily used in.', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cement', 'Cement'), ('steel', 'Steel & TMT Bars'), ('brick', 'Bricks & Blocks'), ('sand', 'Sand'), ('aggregate', 'Aggregate'), ('tile', 'Tiles & Flooring'), ('paint', 'Paint & Coatings'), ('waterproofing', 'Waterproofing'), ('concrete', 'Concrete'), ('hardware', 'Fasteners & Hardware'), ('wood', 'Wood & Timber'), ('roofing', 'Roofing'), ('windows', 'Windows & Doors'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('plaster', 'Plaster & Finishes'), ('fixtures', 'Fixtures & Fittings')], db_index=True, max_length=20),
        ),
    ]
