# Generated by Django 6.0.2 on 2026-02-12 19:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='Kerala', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 9-15 digits. Can start with +.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('contractor', 'Contractor'), ('architect', 'Architect'), ('interior_designer', 'Interior Designer')], default='customer', max_length=20),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.CreateModel(
            name='ServiceProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('total_projects_completed', models.PositiveIntegerField(default=0)),
                ('typical_project_duration', models.CharField(blank=True, help_text="e.g., '6-12 months', '2-4 weeks'", max_length=100)),
                ('specializations', models.JSONField(blank=True, default=list, help_text='List of specialization codes')),
                ('price_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_unit', models.CharField(default='per sqft', help_text="e.g., 'per sqft', 'per project', 'per hour'", max_length=20)),
                ('office_address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True, help_text='Admin notes about the verification decision')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('id_proof', models.FileField(blank=True, help_text='Government ID (Aadhaar, PAN, etc.)', upload_to='verification_docs/id_proofs/%Y/%m/')),
                ('license_document', models.FileField(blank=True, help_text='Professional license, registration certificate, etc.', upload_to='verification_docs/licenses/%Y/%m/')),
                ('portfolio_document', models.FileField(blank=True, help_text='Portfolio PDF or work samples', upload_to='verification_docs/portfolios/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_provider_profiles',
            },
        ),
    ]
