# Generated by Django 6.0.2 on 2026-02-25 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_user_bio_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who approved or rejected this provider', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_providers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_description', models.TextField(blank=True)),
                ('project_location', models.CharField(blank=True, max_length=200)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('project_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('renovation', 'Renovation')], default='residential', max_length=50)),
                ('project_size', models.CharField(blank=True, help_text="e.g., '2500 sq ft', '4 BHK villa'", max_length=100)),
                ('budget_range', models.CharField(blank=True, choices=[('budget', 'Budget (< ₹20L)'), ('mid', 'Mid-range (₹20–50L)'), ('premium', 'Premium (₹50L–1Cr)'), ('luxury', 'Luxury (> ₹1Cr)')], max_length=50)),
                ('image', models.ImageField(upload_to='portfolio/%Y/%m/')),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolio_images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=200)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_phone', models.CharField(blank=True, max_length=15)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
