# Generated by Django 6.0.2 on 2026-03-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_serviceproviderprofile_verified_by_portfolioimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Profile banner image (recommended: 1400×350px)', null=True, upload_to='provider_banners/'),
        ),
    ]
