"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os

GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '')
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    'ourhome-production-2ac9.up.railway.app', 
    '127.0.0.1', 
    'localhost',
    'daring-creativity-production.up.railway.app' # Adding this as a backup based on your project name
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required by django-allauth for multi-site support

    # Third-party apps
    'allauth',                # Core authentication library
    'allauth.account',        # Email-based account management (signup, login, verify, reset)
    'allauth.socialaccount',  # Social login (Google, Facebook) - configured later
    'django_htmx',            # Detects HTMX requests in views via request.htmx
    'crispy_forms',           # Renders Django forms as styled HTML automatically
    'crispy_bootstrap5',      # Bootstrap 5 template pack for crispy-forms

    # Project apps
    'apps.users',
    'apps.products',
    'apps.contractors',
    'apps.designers',
    'apps.shops',        # Future Phase 6: "Where to Buy" local shop directory
    'apps.verifier',
    'apps.reviews',
    'apps.reservations',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Required by allauth - handles account state
    'django_htmx.middleware.HtmxMiddleware',         # Adds request.htmx boolean to every request
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# REPLACED THE DEFAULT DATABASE WITH MYSQL:
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}
# REMEMBER to run : pip install mysqlclient, a 3rd party package to connect Django with MySQL

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Static files
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static'] # Added for static files
STATIC_ROOT = BASE_DIR / 'staticfiles' # Added for static files collection

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media' # Added for media files

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# File upload size limit (5MB)
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB - prevents huge file uploads

# ============================================================
# DJANGO-ALLAUTH CONFIGURATION
# allauth handles: signup, login, logout, email verification,
# password reset, social login (Google/Facebook)
# ============================================================

# Required by allauth - identifies which Site object to use
# After running migrate, go to /admin/sites/site/ and update the domain
SITE_ID = 1

# Authentication backends - tells Django HOW to verify a user's identity
# ModelBackend = Django's default (checks username/password against the DB)
# AuthenticationBackend = allauth's backend (adds email-based auth, social auth)
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# allauth behavior settings (updated to v65+ format):
ACCOUNT_LOGIN_BY_CODE_ENABLED = False       # No magic link / code login
ACCOUNT_LOGIN_METHODS = {'email'}           # Login with email (not username)
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']  # Required signup fields
ACCOUNT_EMAIL_VERIFICATION = 'none'         # No email verification � log in immediately after signup
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'  # Our User model still has username field
ACCOUNT_ADAPTER = 'apps.users.adapters.AccountAdapter'  # Our custom adapter (creates username from email)
ACCOUNT_FORMS = {
    'signup': 'apps.users.forms.CustomerSignupForm',  # Our custom signup form with phone, name fields
}

# LOGIN/LOGOUT URLS - now handled by allauth at /accounts/
LOGIN_URL = '/accounts/login/'         # Where @login_required redirects unauthenticated users
LOGIN_REDIRECT_URL = '/dashboard/'     # Where to go after successful login
LOGOUT_REDIRECT_URL = '/'             # Where to go after logout
ACCOUNT_LOGOUT_REDIRECT_URL = '/'     # allauth's version of the same setting

# Email backend:
# 'console' prints emails to terminal - perfect for development (you see the verification link)
# In production, switch to SMTP (Gmail, AWS SES, Mailgun, etc.)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# ============================================================
# CRISPY FORMS CONFIGURATION
# Renders Django forms as styled HTML using Bootstrap 5 classes
# ============================================================
CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'

# ============================================================
# GROQ API — AI Bill Analyzer
# Add GROQ_API_KEY=... to your .env file
# ============================================================
GROQ_API_KEY = os.getenv('GROQ_API_KEY', '')
