# Generated by Django 6.0.2 on 2026-02-23 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_fix_category_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], help_text='1 (terrible) to 5 (excellent)')),
                ('title', models.CharField(help_text="Short summary. Example: 'Perfect for coastal Kerala construction'", max_length=120)),
                ('review_text', models.TextField(help_text='Minimum 100 characters. Describe your actual experience.')),
                ('reviewer_name', models.CharField(help_text='Display name shown on the review card.', max_length=100)),
                ('reviewer_city', models.CharField(blank=True, max_length=100)),
                ('reviewer_state', models.CharField(blank=True, max_length=100)),
                ('reviewer_type', models.CharField(choices=[('homeowner', 'Homeowner'), ('contractor', 'Contractor'), ('architect', 'Architect'), ('designer', 'Interior Designer'), ('engineer', 'Civil Engineer')], default='homeowner', max_length=20)),
                ('climate_type', models.CharField(blank=True, choices=[('hot_dry', 'Hot & Dry'), ('coastal_humid', 'Coastal & Humid'), ('heavy_rainfall', 'Heavy Rainfall'), ('cold_hilly', 'Cold & Hilly'), ('cyclone_prone', 'Cyclone-Prone Coast')], help_text="Reviewer's climate zone. Powers the 'Used in: Coastal Kerala' badge.", max_length=20)),
                ('use_case', models.CharField(blank=True, help_text="What was this used for? Example: 'Foundation of 2-storey house in Kochi'", max_length=200)),
                ('helpful_count', models.PositiveIntegerField(default=0, help_text="'Was this review helpful?' upvotes. Higher = shown first.")),
                ('is_approved', models.BooleanField(db_index=True, default=False, help_text='Only approved reviews appear on the product page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-helpful_count', '-created_at'],
                'indexes': [models.Index(fields=['product', 'is_approved'], name='review_product_approved_idx')],
            },
        ),
    ]
